on: [push, pull_request]

jobs:
  escritorio_build:
    runs-on: ubuntu-latest
    name: A job to build and push escritorio
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check directory
        run: ls -lat
      - name: build action
        id: build
        uses: ./escritorio/
        with:
          echo-output: 'Test escritorio action'
      - name: init2commit action
        uses: ./github/init2commit
        with:
          email: 'mikiyaf.business@gmail.com'
          directory: '.'
          branch: 'master'
          test: 'test'
      - name: push action
        uses: ./github/push
        with:
          test: 'test'
